{
 "title": "API number counter (TCP) comparison",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Processed count",
   "type": "graph",
   "description": "The number of processed operations ADD",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(research_cmb_processed_operations_processed[2m])",
     "legendFormat": "mutex-based"
    },
    {
     "expr": "rate(research_clf_processed_operations_processed[2m])",
     "legendFormat": "lock-free"
    }
   ]
  },
  {
   "title": "Failed count",
   "type": "graph",
   "description": "The number of failed operations ADD",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(research_cmb_processed_operations_failed[2m])",
     "legendFormat": "mutex-based"
    },
    {
     "expr": "rate(research_clf_processed_operations_failed[2m])",
     "legendFormat": "lock-free"
    }
   ]
  },
  {
   "title": "Duration (nanos)",
   "type": "graph",
   "description": "The duration of one processed operation ADD",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(research_cmb_processed_operations_duration_bucket[2m])) by (le))",
     "legendFormat": "mutex-based"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(research_clf_processed_operations_duration_bucket[2m])) by (le))",
     "legendFormat": "lock-free"
    }
   ]
  }
 ]
}