global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
# - "first.rules"
# - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - 'api-tcp-counter-mutex-based:8080'
          - 'api-tcp-counter-lock-free:8080'
          - 'localhost:9090'